apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: training-tracing
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
      useRequestIdForTraceSampling: false
