## @param gateway-eastwest [object] East-west gateway and network overrides
##
gateway-eastwest:
  revision: green
  networkGateway: network1
  replicaCount: 3
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits: null
  enabled: true
  name: gateway-eastwest
