# Based on Karakoram GitOps values; see README for cluster-specific settings.
revision: green
provider: default
cniBinDir: /home/kubernetes/bin
excludeNamespaces:
- kube-system
chained: true
ambient:
  enabled: false
repair:
  enabled: true
  labelPods: false
  deletePods: false
  repairPods: true
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits: null
resourceQuotas:
  enabled: true
global:
  logging:
    level: info
  logAsJson: true
  defaultResources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits: null
  nativeNftables: false
