revision: green
cniBinDir: /home/kubernetes/bin
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits: null
resourceQuotas:
  enabled: true
global:
  logAsJson: true
  defaultResources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits: null
