## @section Sidecar common parameters
## @param nameOverride Override the parent Sidecar chart name
##
nameOverride: ""
## @param commonLabels [object] Templatable labels on the parent Sidecar
##
commonLabels: {}
## @param commonAnnotations [object] Templatable annotations on the parent Sidecar
##
commonAnnotations: {}

## @section Sidecar parameters
sidecar:
  ## @param sidecar.enabled Create the default Sidecar after the bootstrap stage
  ##
  enabled: true
  ## @param sidecar.labels [object] Templatable Sidecar labels; override commonLabels
  ##
  labels: {}
  ## @param sidecar.annotations [object] Templatable Sidecar annotations; override commonAnnotations
  ##
  annotations: {}
  ## @param sidecar.spec [object] Templatable Istio Sidecar spec
  ##
  spec:
    egress:
      - hosts:
          - "./*"
          - "istio-system/*"

## @section Telemetry parameters
telemetry:
  ## @param telemetry.enabled Create mesh-wide telemetry after bootstrap
  ##
  enabled: true
  ## @param telemetry.labels [object] Templatable labels overriding commonLabels
  ##
  labels: {}
  ## @param telemetry.annotations [object] Templatable annotations overriding commonAnnotations
  ##
  annotations: {}
  ## @param telemetry.spec [object] Templatable Istio Telemetry spec
  ##
  spec:
    metrics:
      - providers:
          - name: prometheus
    tracing:
      - providers:
          - name: otel
        randomSamplingPercentage: 100
        useRequestIdForTraceSampling: false
