# Based on Playground gateway values; participant-specific labels removed.
name: gateway-blue
revision: blue
replicaCount: 1
podAnnotations:
  sidecar.istio.io/inject: 'true'
  sidecar.istio.io/proxyCPU: 10m
  sidecar.istio.io/proxyMemory: 16Mi
rbac:
  enabled: true
serviceAccount:
  create: true
autoscaling:
  enabled: false
service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: Internal
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
labels:
  istio: gateway-blue
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits: null
