apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway-eastwest
  namespace: istio-eastwest-system
spec:
  selector:
    istio: gateway-eastwest
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"
