## @section istiod-blue dependency overrides
## @param istiod-blue [object] Values for the upstream chart
##
istiod-blue:
  revision: blue
  enabled: true
  autoscaleMax: 3
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits: null
  cni:
    enabled: true
  global:
    defaultPodDisruptionBudget:
      enabled: false
    defaultResources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits: null
    proxy:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits: null
    waypoint:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits: null
  pdb:
    minAvailable: 0
  meshConfig:
    enableTracing: true
    extensionProviders:
    - name: otel
      opentelemetry:
        service: alloy.alloy-system.svc.cluster.local
        port: 4317
    defaultConfig:
      tracing:
        sampling: 100
  autoscaleMin: 3
